name: my-job

on: [push]

jobs:
  my-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: test github acitons
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: docker test
      run: |
        node -v
        docker images
    - name: change directory
      working-directory: './golang'
      run: |
        ls
      env:
        CI: true
